### ISSUE TITLE
latest version; KeyError: MTS

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#28]
Hi. I tried the latest version.
Fresh pull. Log show. Hope this helps.
It ran on 54 movies. Interestingly 5 movies were processed correctly. All other errored out.

2021-05-02 11:20:19 | stdout | KeyError: 'MTS'
-- | -- | --
2021-05-02 11:20:19 | stdout | File "BetterCovers.py", line 55, in generateTasks
2021-05-02 11:20:19 | stdout | File "BetterCovers.py", line 183, in processFolder
2021-05-02 11:20:19 | stdout | File "threading.py", line 865, in run
2021-05-02 11:20:19 | stdout | File "threading.py", line 917, in _bootstrap_inner
2021-05-02 11:20:19 | stdout | Traceback (most recent call last):
2021-05-02 11:20:19 | stdout | Exception in thread Thread-7:
2021-05-02 11:20:19 | stdout |  
2021-05-02 11:20:19 | stdout | KeyError: 'MTS'
2021-05-02 11:20:19 | stdout | File "BetterCovers.py", line 55, in generateTasks
2021-05-02 11:20:19 | stdout | File "BetterCovers.py", line 183, in processFolder
2021-05-02 11:20:19 | stdout | File "threading.py", line 865, in run
2021-05-02 11:20:19 | stdout | File "threading.py", line 917, in _bootstrap_inner
2021-05-02 11:20:19 | stdout | Traceback (most recent call last):
2021-05-02 11:20:19 | stdout | Exception in thread Thread-6:
2021-05-02 11:20:18 | stdout |  
2021-05-02 11:20:18 | stdout | KeyError: 'MTS'
2021-05-02 11:20:18 | stdout | File "BetterCovers.py", line 55, in generateTasks
2021-05-02 11:20:18 | stdout | File "BetterCovers.py", line 183, in processFolder
2021-05-02 11:20:18 | stdout | File "threading.py", line 865, in run
2021-05-02 11:20:18 | stdout | File "threading.py", line 917, in _bootstrap_inner
2021-05-02 11:20:18 | stdout | Traceback (most recent call last):
2021-05-02 11:20:18 | stdout | Exception in thread Thread-4:
2021-05-02 11:20:13 | stdout | PROCESSING 54 FOLDERS
2021-05-02 11:19:42 | stdout | [92mSuccesfully downloaded default config file[0m

**Comment by ilarramendi** [comment]
This error looks like you are using the latest version of the config file with an older version of the script, sice the key "MTS" was renamed to "MTC" on the latest push, ill probably add a parameter to the config file to check if it matches the version of the script!

**Comment by ilarramendi** [comment]
Cant recreate with a fresh pull of the latest version of the script, this will be fixed when i create the next executable, closing.

**Comment by michpas** [comment]
> This error looks like you are using the latest version of the config file with an older version of the script, sice the key "MTS" was renamed to "MTC" on the latest push, ill probably add a parameter to the config file to check if it matches the version of the script!
> 
> PD: Are you using the executable or the python script?

Hi. I was using the docker version

**Comment by michpas** [comment]
Hi. Refreshed the docker today; same results.
Note: I can't really get into the docker itself (to update any script) on Synology as they docker starts and fully closes when the better-cover script is done. I guess I have to wait for a docker-update, to pull in the latest

ps. like the idea of adding a version number to the config file so that you can enforce alignment between the script and the config file. Great idea.

**Comment by ilarramendi** [comment]
Hey! Working on a major update to refactor most if the code to make it more consistant, also moved the config  file to inside the executable, instead of downloading, this should fix the problem with older versions.
Ill let you know when the docker is ready, thanks for all the testing!!

**Comment by ilarramendi** [comment]
Hello! A new version of the container is available with the tag: `ilarramendi/better-covers:develop`!
There is a known bug where sometimes it says:
```
Exception in thread Thread-447:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "functions.py", line 421, in generateIMage2
TypeError: can only concatenate list (not "str") to list
```
This will be fixed on the non-develop release!
First run might be a bit slower but the second should be much faster since i added a db file to store all the metadata from libraries!

**Comment by michpas** [comment]
Great. Will test the better-covers:develop version
Did a full clean install. 
Findings:
1. In a fresh install (when the /config folder is empty) the program immediately starts to process the posters. This is ok, but doesn't leave room for the user to make any modification on this first run.

2. I also indeed got the above error a few times.

3.  I noticed in your script & logfile, you still use the word/reference to 'backdrop' (although you correctly process thumb.jpg). That (my mistake) should all be renamed to 'thumb'. Thumb and backdrop are different images and used for different purposes. No need to process these ;-)

4. For info: Processing 443 images around 220 movies tool 6:36 min.  On second run (same folder, with overwrite option)  it took 6:31 min. Roughly the same amount of time. Did you plan/implement something on smart_update (yes/no)
eg. If the cover has been created in past, the video file modifcation date and nfo modification date is same as past, and it's older file, do not reprocess? That would significantly reduce processing time.

5. I checked 'The Gentlemen (2019)'case. It creates poster ok, but doesn't show rotten tomatoes rating. I quess this is due to the fact that RottenTomatoes only has this move 'The gentleman (2020)'. Given the imdb and tmbd uniques codes are in the /nfo file; could this maybe also be used to query the rotten tomatoes rating?   <imdbid>tt8367814</imdbid>  <tmdbid>522627</tmdbid>

6. I also tested it on ''Balloon (2018)'; to see if script takes the imdbid and tmdbid from nfo file. 

Get the following line: interesting is the last line: No results found on TMDB for: 

2021-05-07 06:42:36 | stdout | KeyError: 'mediainfo'
-- | -- | --
2021-05-07 06:42:36 | stdout | File "BetterCovers.py", line 34, in generateTasks
2021-05-07 06:42:36 | stdout | File "BetterCovers.py", line 130, in processFolder
2021-05-07 06:42:36 | stdout | File "threading.py", line 865, in run
2021-05-07 06:42:36 | stdout | File "threading.py", line 917, in _bootstrap_inner
2021-05-07 06:42:36 | stdout | Traceback (most recent call last):
2021-05-07 06:42:36 | stdout | Exception in thread Thread-13:
2021-05-07 06:42:35 | stdout | [93mNo results found on TMDB for: [0m

I'll do some more testing on the actual visuals later the weekend.

**Comment by michpas** [comment]
Hi. I installed a fresh docker better-covers:latest

When running it provides the following error and stops: mediainfo is not installed

**Comment by ilarramendi** [comment]
Hello, i removed mediainfo but forgot to remove the dependency check, should be fixed now!

**Comment by michpas** [comment]
Hi. I pulled the latest docker image. The error with the mediainfo is gone.
Now on new fresh run (config folder empty); I get the below errors for all movies.

![error](https://user-images.githubusercontent.com/66222810/117579528-8fbcf900-b0f3-11eb-91da-eb9bab9cbb67.jpg)

**Comment by ilarramendi** [comment]
This looks like you are using an older version of the config file, you can delete the whole `/config` dir and start the container again!

**Comment by michpas** [comment]
hi. Yes, I guess there was some 'legacy' stuff around. Have deleted all dockers & containers and config.
Started completely new. with latest docker pull.
It runs now without errors. Great achievement !

A question. why did you move from folder.jpg to folder.png? Whats the benefit? From my view, all mediasystems (if you choose to store local art) is using .jpg. For example jellyfin, if you choose to store local art, it saves it as .jpg. I don't think you can even choose to save it as .png.

Will do some more testing, now all is running again

**Comment by ilarramendi** [comment]
This will allow to have transparency on posters in the future (currently not workind due to a problem with the html to img software)
