### ISSUE TITLE
Tried installing and running, but getting an error

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#8]
Hi. Love the concept of this script; but need to understand why it's not working..

Trying to make it integrate with Radarr/Sonarr.

I installed this script within a running 'radarr docker' from linuxserver; 

All manually, via the following steps:
step 1.    apt-get update
step 2:    apt install -y cutycapt
step 3.    apt-get install wget
step 4.    apt-get install xvfb
step 5.    apt-get install mediainfo
Step 6.   wget https://github.com/ilarramendi/Cover-Ratings/releases/download/v0.4-linux/BetterCovers
step 7.   chmod +x BetterCovers
Step 8.  wget https://raw.githubusercontent.com/ilarramendi/Cover-Ratings/main/config.json

Than I ran xvfb-run -a ./BetterCovers '/media/films4K/*' -tmdb xxx -omdb yyyy -o

The message I'm getting is:
                                                                                                                                             
STARTING                                                                                                                                     
Exception in thread Thread-1:                                                                                                                
Traceback (most recent call last):                                                                                                           
  File "threading.py", line 917, in _bootstrap_inner                                                                                         
  File "threading.py", line 865, in run                                                                                                      
  File "BetterCovers.py", line 118, in <lambda>                                                                                              
  File "BetterCovers.py", line 118, in <listcomp>                                                                                            
  File "BetterCovers.py", line 57, in processFolder                                                                                          
  File "functions.py", line 251, in generateImage                                                                                            
  File "functions.py", line 23, in generateCSS                                                                                               
KeyError: 'imgWidth'                                                                                                                         
         
It seems to start fine, but errors out; with  imgWidth.  What is going wrong?

--
If this gets working I would like to experiment with:
*) Installing all scripts automaticly on creation of the docker (possible with linuxserver docker versions)
*) and adding a  'connection string' from Radarr to this script for the newest downloaded materials.
*) This would make it a really good user experience.
*) In addition, it would be great to be able to pass the folder of the config.json in the launch parameter; This would allow the config file to be stored in the docker /config/ folder (that stays persistent) when a new docker pull release is executed.

Thanks !

**Comment by ilarramendi** [comment]
Hello!
The problem you where having should be fixed if you download the version [latest-linux](https://github.com/ilarramendi/Cover-Ratings/releases/tag/latest-linux).
Just created a simple docker image and fixed a couple of bugs, its still a WIP, since its my first time creating a docker image, you can check it out [here](https://hub.docker.com/r/ilarramendi/better-covers).
i'll probably add this to a fork of the radarr/sonarr image from linuxserver to make it automatic as you said, with the 'connecting string'
I also added the option to pass the config file with: `-c ./config.json`
Thaks for these suggestion, any additional idea is welcome!

**Comment by michpas** [comment]
Hi. 
I rerun steps 6..8
Step 6. wget https://github.com/ilarramendi/Cover-Ratings/releases/download/v0.4-linux/BetterCovers
step 7. chmod +x BetterCovers
Step 8. wget https://raw.githubusercontent.com/ilarramendi/Cover-Ratings/main/config.json
Than I ran xvfb-run -a ./BetterCovers '/media/films4K/*' -tmdb xxx -omdb yyyy -o

Same error:
STARTING                                                                                                                                     
Exception in thread Thread-1:                                                                                                                
Traceback (most recent call last):                                                                                                           
  File "threading.py", line 917, in _bootstrap_inner                                                                                         
  File "threading.py", line 865, in run                                                                                                      
  File "BetterCovers.py", line 118, in <lambda>                                                                                              
  File "BetterCovers.py", line 118, in <listcomp>                                                                                            
  File "BetterCovers.py", line 57, in processFolder                                                                                          
  File "functions.py", line 251, in generateImage                                                                                            
  File "functions.py", line 23, in generateCSS                                                                                               
KeyError: 'imgWidth'   

Anything I can do to debug/help?

I'll try the docker separately

**Comment by michpas** [comment]
Hi. Thanks. I tried:

Step 6. wget https://github.com/ilarramendi/Cover-Ratings/releases/download/v0.5-linux/BetterCovers
This gives an error: 
'' /# wget https://github.com/ilarramendi/Cover-Ratings/releases/download/v0.5-linux/BetterCovers               
--2021-04-26 10:49:14--  https://github.com/ilarramendi/Cover-Ratings/releases/download/v0.5-linux/BetterCovers                              
Resolving github.com (github.com)... 140.82.121.4                                                                                            
Connecting to github.com (github.com)|140.82.121.4|:443... connected.                                                                        
HTTP request sent, awaiting response... 404 Not Found                                                                                        
2021-04-26 10:49:14 ERROR 404: Not Found.  ''

Than I tried:

step 6. wget https://github.com/ilarramendi/Cover-Ratings/releases/tag/latest-linux/BetterCovers
step 7. chmod +x BetterCovers

Which clearly works, but am not sure if this gives me the 0.5 or 0.4 version
I ran xvfb-run -a ./BetterCovers '/media/films4K/*' -tmdb xxx -omdb yyyy -o
But same results:
Exception in thread Thread-1:                                                                                                                
Traceback (most recent call last):                                                                                                           
  File "threading.py", line 917, in _bootstrap_inner                                                                                         
  File "threading.py", line 865, in run                                                                                                      
  File "BetterCovers.py", line 118, in <lambda>                                                                                              
  File "BetterCovers.py", line 118, in <listcomp>                                                                                            
  File "BetterCovers.py", line 57, in processFolder                                                                                          
  File "functions.py", line 251, in generateImage                                                                                            
  File "functions.py", line 23, in generateCSS                                                                                               
KeyError: 'imgWidth'    

Hope this helps.
Will try the docker later

**Comment by ilarramendi** [comment]
latest-linux is v0.5.
Can you send me a copy of the dockerfile to take a look and try it myself?
I think this error is because for some reason you are still using v0.4 with a config file of v0.5

**Comment by michpas** [comment]
You are right. There are still traces in the docker of the old v.04 and new v.05 version.
To avoid contamination, I'll start with a fresh recreation of (linuxserver) Radarr docker and followed the below add-on steps:

step 1. apt-get update
step 2: apt install -y cutycapt
step 3. apt-get install wget
step 4. apt-get install xvfb
step 5. apt-get install mediainfo
step 6. wget https://github.com/ilarramendi/Cover-Ratings/releases/tag/latest-linux/BetterCovers
step 7. chmod +x BetterCovers
Step 8. wget https://raw.githubusercontent.com/ilarramendi/Cover-Ratings/main/config.json

than ran: xvfb-run -a ./BetterCovers '/media/films4K/*' -tmdb xxxx -omdb yyy  -o
This gives me the following:

root@linuxserver-radarr_films4k:/# xvfb-run -a ./BetterCovers '/media/films4K/*' -tmdb xxx-omdb yyy -o     
./BetterCovers: 8: Syntax error: newline unexpected                                                                                          
root@linuxserver-radarr_films4k:/# ^C         

Syntax error. newline expected.
Hope this helps

**Comment by ilarramendi** [comment]
Can you try with a clean install following the steps i commented [here](https://github.com/ilarramendi/Cover-Ratings/issues/7#issuecomment-827268940)? Or even use that dockerfile since i think thats what you where trying to achive.

**Comment by michpas** [comment]
Hi. I installed radarr clean.

Executed within the installed container:
apt-get -y update
apt-get install -y cutycapt xvfb mediainfo ffmpeg wget
wget 'https://github.com/ilarramendi/Cover-Ratings/releases/download/v0.6-linux/BetterCovers' -q
chmod +x '/BetterCovers'
mkdir /tmp/runtime
chmod 0700 /tmp/runtime
set XDG_RUNTIME_DIR /tmp/runtime

When running; I get the following error: Indexerror, list index out of range

xvfb-run -a ./BetterCovers '/media/films4K/*' -tmdb xxxx -omdb yyyy -o     
Traceback (most recent call last):                                                                                                           
  File "BetterCovers.py", line 123, in <module>                                                                                              
IndexError: list index out of range

**Comment by ilarramendi** [comment]
Overwrite needs to be a boolean to work ok with the docker container, try `-o true` instead

**Comment by michpas** [comment]
Thanks.
xvfb-run -a ./BetterCovers '/media/films4K/*' -tmdb xxxx -omdb yyyy   -o true
That did the trick !!
It ran fine for all 4 movies out of 4. 
It also picked up the folder as well as the backdrop images. If you are not sure what people will use wrt folder/poster or backdrop, you might make this selection flexible as a parameter.
and I can see the image quality is much better

Example output images are:
![backdrop](https://user-images.githubusercontent.com/66222810/116285725-b479ae00-a78e-11eb-96ed-7fc4c8ea4d37.jpg)
![folder](https://user-images.githubusercontent.com/66222810/116285733-b7749e80-a78e-11eb-9db4-11cf2563636f.jpg)

If I run the routine again, it starts to process from scratch (eg. query the api etc). 
and teh script is also impactfull on system, so when having a large database, its important to do the creation as  efficiently.
For example if you would tag the newly created image via the  exiftool -creatortool="Better-Cover-[date of better cover created + creation date of movie]".
And first maybe 1. check if folder.jpg is available.
If not, run as normal
if yes, check if the creatortool metadata is set on the folder.jpg
     if no, run as normal, but use the existing folder.jpg as standard (eg. no need to query for a new image)
     if yes, test if the main video file has changed (it could be different codex etc) This is tricky as I guess you don't know the filename. As simple fix, maybe the largest mkv file in a folder (and as optimizer, store the filename in the creatortool paramter, so you only query it ones?)? A better more fool-proof would be a API query to Radarr/Sonarr
              if yes (video file has changed) run full image extraction and overlay routine.
              if no, video file is the same; however the rating might have changed. the ratings changes often for new movies, but for older movies that doesn't happen that much. Here a 'smart' algoritme might be good. Eg. one that refreshes the image more often, the younger the movie is. For example is new creation date <15 days refresh daily. 15><30 days: weekly, 30><90 days, monthy: 30><90 quarterly.  of something like this. Could maybe also set with parameters.

Just food for thought from an energized colleague, with passion for the smart and user friendly solutions.
:-)

**Comment by ilarramendi** [comment]
Wow, thanks for the feedback, currently im working in an update to add language, age ratings, using ffprobe instead of mediainfo (since its already installed with ffmpeg), better logs, only executing the metadata extraction (most resource intensive part of the script) and accesing the servers if a poster is not found, added a tag to the image with the idea like you said in the future to be able to use custom posters, and a couple of bug fixes!
Also im looking for a way to download textless posters, since i think they look much cooler!
Thank you a lot for all your suggestions!

Pd: The covers on high resolution look realy nice!

**Comment by michpas** [comment]
Great to hear on these improvements and the switch to ffprobe instead of mediainfo.
Looking forward to new releases !
